title = "In pausa"
baseURL = "https://fpiantini.it/"
languageCode = "it-it"
theme = "ananke"
MetaDataFormat = "yaml"
DefaultContentLanguage = "it"
SectionPagesMenu = "principale"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Durante le pause l'importante è fare qualcosa"
  facebook = "https://www.facebook.com/fpiantini"
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/fpiantini/"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/fpiantini/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/landmannalaugar.jpg"
  recent_posts_number = 2

